### ISSUE TITLE
Comparison with hvPlot

### ISSUE THREAD

**Issue by jbednar** [martinfleis/geopandas-view#45]
This looks cool! Folium provides lots of useful stuff that's of value for Geopandas. I'm curious about the extent to which it can be said to be interactive, compared to existing interactive .plot approaches like [hvPlot](https://hvplot.holoviz.org/user_guide/Geographic_Data.html) for Geopandas. Obviously the resulting Leaflet plots are interactive at the browser level in JavaScript, i.e. supporting pan/zoom/hover, but can it support Python-based interactivity where you e.g. click on a shape and call a Python function dynamically to reveal things about it? As I understood it Folium does not offer such capabilities and thus neither will geopandas-view?

**Comment by martinfleis** [comment]
You can show attributes of each geometry either as a `tooltip` (on hover) or `popup` (on click). Check the second example in this notebook https://nbviewer.jupyter.org/github/martinfleis/geopandas-view/blob/main/examples.ipynb. You can show all columns (`tooltip=True`), pass a list of columns you want to show or `n` first columns to both `tooltip` and `popup`.

Is that what you mean?

---

I think it would be great to have a deeper comparison of bokeh and leaflet plots because I think they both have their benefits and drawbacks and would be certainly helpful to point users towards `hvPlot` if you e.g. need to plot larger dataframes (that is where leaflet can struggle). I bet there are other use cases where it is a better choice.

On a related note, we're still discussing the potential API for this (it won't be `view` in the end, that is for sure) and one idea is to open potential built-in interactive plotting to other backends, exactly as you can do (and holoviews does) with pandas. One could be `hvPlot`, other `ipyleaflet`... We would then only need a layer in between which would link `hvPlot` API to geopandas plotting API. To allow you all these with the same signature:

```py

view(gdf, column='foo', cmap='viridis', legend=True, backend='folium')
view(gdf, column='foo', cmap='viridis', legend=True, backend='ipyleaflet')
view(gdf, column='foo', cmap='viridis', legend=True, backend='hvplot')

# or ideally with some global switch

gpd.options.plotting.backend = "backend.module"
```

**Comment by jbednar** [comment]
Making the backend configurable as discussed in https://github.com/geopandas/geopandas/issues/1904 is a great idea.

> Is that what you mean?

Not exactly, no.  I suppose the difference I'm trying to articulate is between "canned (but configurable) Javascript-based interactivity" and "custom Python-backed interactivity". 

In hvPlot and other Bokeh-based tools, you can very easily tie any event that occurs in the browser to any arbitrary code to run on the Python process. E.g. if I click on a US state in a map, it might run Python code to show the 10 most recent tweets mentioning that state, or to send an email to the governor of that state, or literally anything else I can dream up to do. I've only used Folium a little, but I don't think it can support that; as I understand it it uses Python to construct the map but then doesn't have a mechanism to get events or data back to Python from the map. hvPlot, in contrast, uses Bokeh, Panel, and HoloViews to mirror data and events bidirectionally between JS and Python, making it much simpler for a Python programmer (such as most GeoPandas users!) to create custom interactive maps.  I believe ipyleaflet is similar to hvPlot in this respect, though it requires a Jupyter kernel while hvPlot can also use a fully separate Bokeh server that is more practical for deployments.

So for my purposes as a Python programmer, I see a Folium-based map as being very limited in the interactivity it can support; very useful compared to a PNG, but still only able to provide basic interactivity. I'm in no way a Folium or Leaflet expert, though!

**Comment by martinfleis** [comment]
Ahh. You're right! Folium (and I believe leaflet.js itself) does not support this kind of interactivity as far as I am aware. One more reason to do the customisable backend and properly document what hvPlot backend can do somewhere in geopandas docs. 

The goal of `geopandas-view` is to provide an easy lightweight way of data exploration, not much more than that. We're happy to leave all these fancy functions to hvPlot or ipyleaflet :).
