### ISSUE TITLE
Correcting for different CRS?

### ISSUE THREAD

**Issue by michaelSederlin** [martinfleis/geopandas-view#46]
This is really cool, and easy to use. 

I stumbled onto something which I'm not sure if it's is a bug or a feature. 
I am able to plot geodataframes with different crs in view but not with the normal geopandas plotting API. 
If it indeed is a feature of either folium or gpd, maybe it's problematic that this is done silently?

![image](https://user-images.githubusercontent.com/37883908/114897748-d465b500-9e11-11eb-82d5-14b6aba8e47f.png)
![image](https://user-images.githubusercontent.com/37883908/114897295-615c3e80-9e11-11eb-98ba-68884edd31dd.png)

**Comment by martinfleis** [comment]
That is a feature but you're right that we should at least mention it in the docstring. XYZ tiles (background tiles) almost exclusively use Web Mercator (EPSG 3857) projection. Therefore to be able to use them, we by default reproject everything to 3857 before passing it to folium. And folium actually does the same if you pass it a GeoDataFrame. 

You can force it not to do the conversion by passing `crs="Simple"` and ideally `tiles=None` because otherwise it gets broken. In this case, you pass the custom tiles if you have XYZ source in the projection you need.

```py
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
view(gdf, crs="Simple", tiles=None)
```
<img width="1104" alt="Screenshot 2021-04-15 at 19 26 04" src="https://user-images.githubusercontent.com/36797143/114919649-6d9bc800-9e20-11eb-8f18-d60af10deb13.png">

I believe that this is the correct default to use. If we didn't reproject under the hood, the vast majority of plots would come without background tiles, which is not what we want here. 

`crs` attribute is passed to `folium.Map`, so you can check more details in their docs https://python-visualization.github.io/folium/modules.html#folium.folium.Map.

**Comment by michaelSederlin** [comment]
Oh, yeah that makes sense. 
It made me confused when I was trying to do some operations with the dataframes since I forgot I had reprojected one and assumed they were in the same coordinate systems after the plotting worked.

**Comment by jorisvandenbossche** [comment]
One question related to this: if you specify a `crs` to folium, do you need to guarantee yourself that the tiles use that CRS? Eg if you specify `crs="EPSG4326"`, but use one of the typical tile providers that use 3857, then you get a mismatch? (it seems so, from quickly testing)

**Comment by martinfleis** [comment]
> if you specify a crs to folium, do you need to guarantee yourself that the tiles use that CRS? 

@jorisvandenbossche Yes. 

 We can't warp it as we do in contextily in an interactive environment.
